output
====================== RESTART: C:/Users/HP/factorial2.py ======================
The factorial of 4 is 24

====================== RESTART: C:/Users/HP/factorial2.py ======================
The factorial of 0 is 1

====================== RESTART: C:/Users/HP/factorial2.py ======================
Sorry, factorial does not exist for negative numbers

====================== RESTART: C:/Users/HP/factorial2.py ======================
The factorial of 1 is 1

====================== RESTART: C:/Users/HP/factorial2.py ======================
Traceback (most recent call last):
  File "C:/Users/HP/factorial2.py", line 1, in <module>
    num = Q
NameError: name 'Q' is not defined